server:
  port: 8082

spring:
  application:
    name: api-gateway
  data:
    mongodb:
      uri: mongodb://localhost:28017/userdb
      auto-index-creation: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2
            - id: company-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/companies/**
              filters:
                - StripPrefix=2
          globalcors:
            cors-configurations:
              '[/**]':
                allowedoriginpatterns: "*"
                allowedmethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedheaders: "*"
                allowcredentials: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG